dataset:
  ucf_crime:
    annotation_file: "data/ucf-crime/annotations.txt"
    videos_dir: "data/ucf-crime/videos"

  view360:
    annotation_file: "data/view360/annotations.txt"
    videos_dir: "data/view360/videos"

  ped1:
    annotation_file: "data/ped1/annotations.txt"
    videos_dir: "data/ped1/videos"

  ped2:
    annotation_file: "data/ped2/annotations.txt"
    videos_dir: "data/ped2/videos"

  dota:
    annotation_file: "data/dota/annotations.txt"
    videos_dir: "data/dota/videos"

  shanghaitech:
    annotation_file: "data/shanghaitech/annotations.txt"
    videos_dir: "data/shanghaitech/videos"

  ubnormal:
    annotation_file: "data/ubnormal/annotations.txt"
    videos_dir: "data/ubnormal/videos"

  avenue:
    annotation_file: "data/avenue/avenue_merge.txt"
    videos_dir: "data/avenue/videos"

eis:
  frame_interval_candidates: [30, 24, 18, 12, 6, 3, 2, 1]
  min_K: 1
  max_K: 3000

entity:
  roles: ["actor", "subject", "related"]
  max_ids_per_role: 10

ui:
  colors:
    actor: "#FF0000"
    subject: "#00FF00"
    related: "#0000FF"
    pos_point: "#00FFFF"
    neg_point: "#FF00FF"

export:
  output_dir: "annotations"
