dataset:
  ucf_crime:
    annotation_file: "data/ucf-crime/annotations.txt"
    videos_dir: "data/ucf-crime/videos"
    original_fps: 30

  xd_violence:
    annotation_file: "data/xd-violence/annotations.txt"
    videos_dir: "data/xd-violence/videos"
    original_fps: 30
    gap_threshold: 5

  view360:
    annotation_file: "data/view360/annotations.txt"
    videos_dir: "data/view360/videos"
    original_fps: 30

  ped1:
    annotation_file: "data/ped1/annotations.txt"
    videos_dir: "data/ped1/videos"
    original_fps: 32

  ped2:
    annotation_file: "data/ped2/annotations.txt"
    videos_dir: "data/ped2/videos"
    original_fps: 32

  dota:
    annotation_file: "data/dota/annotations.txt"
    videos_dir: "data/dota/videos"
    original_fps: 16

  shanghaitech:
    annotation_file: "data/shanghaitech/annotations.txt"
    videos_dir: "data/shanghaitech/videos"
    original_fps: 24

  ubnormal:
    annotation_file: "data/ubnormal/annotations.txt"
    videos_dir: "data/ubnormal/videos"
    original_fps: 30

  avenue:
    annotation_file: "data/avenue/avenue_merge.txt"
    videos_dir: "data/avenue/videos"
    original_fps: 32

eis:
  dt_candidates: [10, 4, 2, 1]
  min_K: 3
  max_K: 15

entity:
  roles: ["actor", "subject", "related"]
  max_ids_per_role: 10

ui:
  colors:
    actor: "#FF0000"
    subject: "#00FF00"
    related: "#0000FF"
    pos_point: "#00FFFF"
    neg_point: "#FF00FF"

export:
  output_dir: "annotations"
